import { NativeModules, Platform, StyleSheet } from 'react-native';
import { COLORS, sh, SIZES, sw, width } from '../../constants/theme';
const { StatusBarManager } = NativeModules;

const createStyles = () =>
  StyleSheet.create({
    keyboardAvoiding: {
      backgroundColor: COLORS.background,
      flex: 1,
      alignSelf: 'center',
      // paddingTop: StatusBarManager.HEIGHT,
      width: '100%',
    },
    header: { height: sh(135) + StatusBarManager.HEIGHT, zIndex: 1000, backgroundColor: COLORS.primary, paddingTop: StatusBarManager.HEIGHT },
    cont: {
      paddingHorizontal: sw(18),
      width: width,
      position: 'absolute',
      bottom: -20,
    },
    textInput: { backgroundColor: COLORS.flbg },
    tabsContainer: {
      width: 214,
      height: sh(40),
      backgroundColor: COLORS.inactiveBtn,
      alignSelf: 'center',
      borderRadius: 22,
      padding: 5,
      flexDirection: 'row',
    },
    tab: {
      width: '50%',
      height: '100%',
      backgroundColor: COLORS.primary,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: sw(30),
      marginBottom: sh(15),
      alignItems: 'center',
    },
    input: {
      borderRadius: 5,
      backgroundColor: COLORS.white,
      borderWidth: 0,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,

      elevation: 2,
    },
    right: {
      flexDirection: 'row',
      alignItems: 'center',
      borderLeftWidth: 0.5,
      borderColor: COLORS.primary,
      padding: 5,
      paddingRight: 15,
    },
    dot: {
      height: sh(4),
      width: sh(4),
      borderRadius: sh(2),
      backgroundColor: COLORS.orange,
      position: 'absolute',
      right: 0,
    },
    locView: {
      flex: 1,
      width: width - sw(36),
      backgroundColor: COLORS.white,
      alignSelf: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },

      shadowOpacity: 0.2,
      shadowRadius: 1.41,
      elevation: 2,
      borderRadius: 10,
      paddingVertical: sh(14),
      marginBottom: sh(14),
    },
    close: {
      textAlign: 'center',
      alignSelf: 'flex-end',
    },
    x: {
      fontSize: 20,
      textAlign: 'center',
      fontWeight: '400',
      position: 'absolute',
      right: sw(12),
      top: -5,
      padding: 5,
    },
    locTextContainer: {
      textAlign: 'center',
      marginBottom: sh(16),
      width: sw(232),
      alignSelf: 'center',
    },
    locText: { fontSize: 14, textAlign: 'center' },
    locButt: {
      borderRadius: 3,
      width: sw(167),
      alignSelf: 'center',
      backgroundColor: COLORS.primary,
    },
    flatlistDetails: {
      alignSelf: 'center',
      width: width,
    },

    num: { color: COLORS.primary, fontSize: 16 },
    img: { marginHorizontal: sw(5) },
    logo: { height: sh(40), width: sw(101) },

    navi: {
      width: width - sw(90),
      height: sh(50),
      position: 'absolute',
      zIndex: 200,
      opacity: 0,
      top: 0,
    },
    twoText: {
      flexDirection: 'row',
      marginHorizontal: sw(18),
      marginBottom: sh(13),
    },
    bottom: {
      backgroundColor: COLORS.white,
      alignSelf: 'center',
      position: 'absolute',
      justifyContent: 'space-between',
      bottom: sh(6),
      width: width - sw(36),
      flexDirection: 'row',
      borderRadius: 7,
      shadowColor: COLORS.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 3,
    },
    sep: {
      height: sh(5),
      backgroundColor: COLORS.orange,
      marginBottom: sh(10),
    },
    mainFlatlist: { paddingTop: sh(34) },
    footer: {
      height: sh(40),
      marginBottom: sh(10),
    },
    noResult: {
      alignSelf: 'center',
      justifyContent: 'center',
      flex: 1,
      alignItems: 'center',
      marginTop: sh(300),
    },
    red: {
      height: sw(55),
      width: sw(55),
      backgroundColor: COLORS.orange,
      borderRadius: sw(27.5),
      alignItems: 'center',
      justifyContent: 'center',
      top: -sh(65),
      zIndex: 100,
    },
    home: {
      alignSelf: 'center',
      marginTop: sh(10),
      marginBottom: sh(25),
    },
    save: { position: 'absolute', bottom: -50 },
    tags: {
      borderWidth: 0.5,
      alignSelf: 'center',
      paddingHorizontal: sw(15),
      paddingVertical: sw(6),
      borderColor: COLORS.inactive,
      borderRadius: 17,
      marginRight: sw(8),
      marginBottom: sw(8),
    },
    tagView: {
      flexWrap: 'wrap',
      flexDirection: 'row',
      borderBottomWidth: 0.3,
      paddingBottom: sw(10),
      borderColor: COLORS.shadow,
    },
    selected: {
      backgroundColor: COLORS.primary,
      borderColor: COLORS.primary,
    },
    saved: {
      borderRadius: 3,
      borderWidth: 0.5,
      paddingHorizontal: sh(14),
      borderColor: COLORS.border,
      marginTop: sh(12),
    },
    show: {
      flex: 1,
      alignSelf: 'center',
      justifyContent: 'flex-end',
      alignItems: 'center',
      paddingVertical: sh(7),
      borderTopLeftRadius: 5,
      borderBottomLeftRadius: 5,
    },
    search: {
      flex: 1,
      paddingVertical: sh(7),
      borderTopRightRadius: 5,
      borderBottomRightRadius: 5,
      alignItems: 'center',
    },
    nameView: {
      flexDirection: 'row',
      marginVertical: sh(12),
    },
    receive: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginVertical: sh(12),
    },
    bottomSheet: {
      justifyContent: 'space-between',
      height: '100%',
      paddingBottom: 40,
    },
    abslute: { bottom: sh(45), width: sw(190) },
    sorting: { width: sw(190) },
    border: { width: '100%', marginBottom: sh(20) },
    name: { flex: 1 },
    bottomSheetSaved: {
      justifyContent: 'space-between',
      height: '100%',
      paddingBottom: 40,
    },
    absluteSaved: { bottom: sh(45), width: sw(190) },
    sortingSaved: { width: sw(190) },
    borderSaved: { width: '100%', marginBottom: sh(17) },
    border2: { width: '100%' },
    savedSaved: {
      borderRadius: 3,
      borderWidth: 0.5,
      borderColor: COLORS.border,
      marginTop: sh(12),
    },
    nameViewSaved: {
      flexDirection: 'row',
      marginVertical: sh(12),
      paddingHorizontal: sh(14),
    },
    receiveSaved: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      // marginVertical: sh(12),
      marginBottom: sh(7),
    },
    selectedP: {
      paddingBottom: 5,
      paddingHorizontal: sh(14),
    },
    res: {
      paddingHorizontal: sh(14),
    },
    daily: {
      alignSelf: 'flex-end',
      alignItems: 'flex-end',
      top: sh(10),
      width: sw(190),
      borderRadius: 5,
    },
    buttonSaved: {
      justifyContent: 'flex-end',
      alignItems: 'center',
      padding: 5,
      marginBottom: sh(14),
    },
    inputSaved: {
      flex: 1,
      height: sh(20),
      padding: 0,
      textAlign: 'right',
      color: COLORS.primary,
      fontWeight: '200',
      fontSize: 13,
    },
    searchSaved: { marginTop: sh(20) },
    nameSaved: { flex: 1 },
    padding: { padding: 5 },
    selectContainer: {
      backgroundColor: COLORS.white
    }
  });

export default createStyles;
