import {NativeModules, Platform, StyleSheet} from 'react-native';
import {COLORS, sh, SIZES, sw, width} from '../../constants/theme';

const createStyles = () =>
  StyleSheet.create({
    keyboardAvoiding: {
      backgroundColor: COLORS.background,
      flex: 1,
      alignSelf: 'center',
      width: '100%',
    },
    rowView: {
      flexDirection: 'row',
      width: '100%',
      height: sh(45),
      alignItems: 'center',
      paddingHorizontal: sw(16),
      marginBottom: sh(20),
    },
    abs: {
      backgroundColor: COLORS.black,
      opacity: 0.3,
      flex: 1,
      width: width,
      height: '100%',
      zIndex: 0,
      borderRadius: 0,
    },
    list: {height: sh(24)},
    back: {},
    map: {
      justifyContent: 'center',
      borderRadius: 10,
      borderColor: COLORS.primary,
      height: sh(40),
      paddingHorizontal: sw(55),
      alignItems: 'center',
      alignSelf: 'center',
    },
    mapText: {
      flex: 1,
      justifyContent: 'center',
    },
    row: {
      flex: 1,
      alignSelf: 'center',
      flexDirection: 'row',
      // alignItems: 'flex-end',
      height: 50,
      marginBottom: 15,
    },
    rowShow: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 15,

      // alignItems: 'flex-end',
      // height: 50,
      // marginBottom: 15,
    },
    arrowDown: {
      alignSelf: 'center',
      justifyContent: 'center',
      marginTop: sh(8),
      marginHorizontal: sh(4),
    },
    shortText: {
      marginTop: sh(5),
      justifyContent: 'center',
    },
    sortView: {
      height: sh(180),
      width: sw(270),
      backgroundColor: COLORS.white,
      position: 'absolute',
      alignSelf: 'center',
      borderRadius: 10,
      top: sh(100),
      zIndex: 2,
      paddingTop: sh(9),
      // paddingBottom: sh(16),
      paddingHorizontal: sh(12),
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    flatlist: {
      flexGrow: 1,
    },
    flatlist2: {
      flexGrow: 1,
      // zIndex: 1,
    },
    flatListText: {
      fontSize: 15,
      marginHorizontal: sw(3),
      // justifyContent: 'center',
    },
    verticalView: {
      marginBottom: sh(8),
      marginHorizontal: sh(16),
      // width: '100%',
      width: sw(374),
      // alignSelf: 'center',
      // resizeMode: 'stretch',
    },
    horizontalView: {
      marginBottom: sh(8),
      marginLeft: sh(16),
      width: sh(200),
    },
    horizontalImg: {
      width: '100%',
      borderRadius: 10,
    },
    virticalText: {fontSize: 22},
    horizontalText: {
      fontSize: 20,
      alignSelf: 'center',
      justifyContent: 'center',
      textAlign: 'center',
    },
    virticalTextSec: {fontSize: 16, marginBottom: sh(3)},
    img: {
      width: sw(100),
      height: sw(100),
      marginHorizontal: 5,
      borderRadius: 10,
      alignSelf: 'center',
    },
    imgView: {marginTop: sh(13)},
    saved: {position: 'absolute', right: sw(31), top: sh(18)},
    aboutRoom: {
      position: 'absolute',
      height: sh(74),
      backgroundColor: COLORS.primary,
      width: sw(374),
      alignSelf: 'center',
      bottom: sh(17),
      opacity: 0.9,
      borderBottomEndRadius: 10,
      borderBottomStartRadius: 10,
      paddingHorizontal: sh(25),
      paddingVertical: sh(1),
    },
    aboutRoomHorizontal: {
      position: 'absolute',
      height: sh(43),
      backgroundColor: COLORS.primary,
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
      width: '100%',
      bottom: 0,
      opacity: 0.9,
      borderBottomEndRadius: 10,
      borderBottomStartRadius: 10,
    },
    semiCircuil: {
      position: 'absolute',
      left: sw(16),
      justifyContent: 'center',
      alignItems: 'center',
      top: sh(18),
      backgroundColor: '#1A8CAF66',
      height: sh(29),
      width: sh(38),
      borderRadius: 12,
      fontSize: 22,
    },
    counter: {
      fontSize: 22,
    },
    recommendation: {
      marginBottom: sh(8),
      marginHorizontal: sh(16),
    },
    seeMore: {
      alignSelf: 'center',
      marginTop: sh(19),
      marginBottom: sh(31),
      marginHorizontal: sh(16),
    },
    button: {
      width: sw(135),
      backgroundColor: COLORS.primary,
      borderColor: COLORS.primary,
      borderRadius: 10,
      marginTop: sh(19),
      alignSelf: 'center',
    },
    modelView: {
      height: sh(200),
      width: width,
      borderTopRightRadius: 25,
      borderTopLeftRadius: 25,
      position: 'absolute',
      backgroundColor: COLORS.white,
      bottom: 0,
      alignSelf: 'center',
      paddingHorizontal: sw(16),
    },
    textAndButton: {
      flexDirection: 'row',
      width: '100%',
      justifyContent: 'space-between',
      marginBottom: sh(16),
    },
    icon: {position: 'absolute', top: -20},
  });

export default createStyles;
