import {StyleSheet, Dimensions, Platform, NativeModules} from 'react-native';
const {width} = Dimensions.get('window');
import {COLORS, height, sh, SIZES, sw} from '../../constants/theme';
const {StatusBarManager} = NativeModules;

export const styles = StyleSheet.create({
  shadow: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  header: {
    borderBottomWidth: 0,
  },
  container: {
    backgroundColor: '#F7F7F7',
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  mapView: {
    width,
    height: height,
    backgroundColor: '#F6F6F6',
  },
  mapStyle: {
    // flex: 1,
    height: Platform.OS == 'android' ? height : height - sh(120),
    backgroundColor: '#F6F6F6',
  },
  nearstLocationItemShadow: {
    width: sw(94),
    position: 'absolute',
    bottom: sh(7),
    alignSelf: 'center',
    borderRadius: 12,
    backgroundColor: '#FFF',
  },
  nearstLocationItem: {
    borderRadius: 12,
    overflow: 'hidden',
    paddingHorizontal: sw(4),
    paddingVertical: sw(5),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nearstLocationItemLocationDetails: {
    flex: 1,
    marginRight: sw(3),
  },
  nearstLocationItemTitle: {
    width: '100%',
    fontSize: 14,
    fontWeight: '600',
    color: '#273746',
    textAlign: 'left',
  },
  nearstLocationItemDesc: {
    width: '100%',
    fontSize: 11,
    fontWeight: '400',
    color: '#8FA0B0',
    textAlign: 'left',
  },
  nearstLocationItemCallBtn: {
    height: sh(5.5),
    aspectRatio: 1,
    backgroundColor: '#F3F5F4',
    borderRadius: sw(2),
    marginRight: sw(2),
    justifyContent: 'center',
    alignItems: 'center',
  },
  nearstLocationItemBtn: {
    width: null,
    height: sh(5.5),
    paddingVertical: sw(2),
  },
  nearstLocationItemBtnTxt: {
    fontSize: 13,
    fontWeight: '600',
  },
  bottomSheetView: {
    position: 'absolute',
    top: 200,
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#FFF',
  },
  flatlistContainer: {
    flexGrow: 1,
    paddingBottom: sh(4),
  },
  flatlistHeader: {
    width: '100%',
    marginBottom: sh(2),
  },
  flatlistHeaderPanPressable: {
    paddingVertical: sh(1.5),
  },
  flatlistHeaderPan: {
    width: sw(14),
    height: sw(2),
    borderRadius: 4,
    backgroundColor: '#888',
    alignSelf: 'center',
  },
  flatlistHeaderTitle: {
    width: '100%',
    fontSize: 20,
    fontWeight: '700',
    color: '#151E26',
    textAlign: 'left',
    paddingHorizontal: sw(4),
    marginTop: sh(3),
  },
  flatlistItem: {
    width: '100%',
    paddingHorizontal: sw(4),
    paddingVertical: sw(5),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(223, 228, 232, 0.5)',
  },
  flatlistItemLocationDetails: {
    flex: 1,
    marginRight: sw(3),
  },
  flatlistItemTitle: {
    width: '100%',
    fontSize: 14,
    fontWeight: '600',
    color: '#273746',
    textAlign: 'left',
  },
  flatlistItemDesc: {
    width: '100%',
    fontSize: 11,
    fontWeight: '400',
    color: '#8FA0B0',
    textAlign: 'left',
  },
  flatlistItemCallBtn: {
    height: sh(5.5),
    aspectRatio: 1,
    backgroundColor: '#F3F5F4',
    borderRadius: sw(2),
    marginRight: sw(2),
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatlistItemBtn: {
    width: null,
    height: sh(5.5),
    paddingVertical: sw(2),
    backgroundColor: '#F3F5F4',
  },
  flatlistItemBtnTxt: {
    fontSize: 13,
    fontWeight: '600',
    color: '#273746',
  },
  textInput: {flex: 1, paddingHorizontal: 10},
  input: {color: COLORS.primary, height: sh(40)},
  mapText: {justifyContent: 'center'},
  map: {
    justifyContent: 'center',
    borderRadius: 10,
    borderColor: COLORS.primary,
    height: sh(40),
    paddingHorizontal: sh(5),
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    alignSelf: 'center',
  },
  back: {
    height: sh(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapIcons: {
    justifyContent: 'center',
    borderRadius: 15,
    borderColor: COLORS.primary,
    height: sh(40),
    paddingHorizontal: sh(11.4),
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    alignSelf: 'center',
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderBottomWidth: 12,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: COLORS.primary,
    transform: [{rotate: '180deg'}],
    justifyContent: 'center',
    alignSelf: 'center',
    top: -1,
  },
  headerView: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    paddingHorizontal: SIZES.smallPadding / 2,
  },
  mapTextPin: {justifyContent: 'center', marginHorizontal: sw(4)},
  mapPin: {
    justifyContent: 'center',
    borderRadius: 10,
    borderColor: COLORS.primary,
    height: sh(40),
    alignItems: 'center',
    backgroundColor: '#6BC043',
    marginTop: sh(16),
    flexDirection: 'row',
    paddingHorizontal: sw(16),
    alignSelf: 'flex-end',
    marginHorizontal: sw(16),
  },
});
